### ISSUE TITLE
Gathering dataset

### ISSUE THREAD

**Issue by urbikn** [urbikn/probing-hierarchical-sentences#1]
From the description in our proposal:
_We will use the data that is provided by the GitHub repositories of Conneau et al. (2018), as well as the already existing code for the probing tasks. Further, we will use the data from the paper by McCoy et al. (2020), where they presumably used the same
data for their experiments as McCoy et al. (2018)._

Conneau et al. (2018) dataset: https://github.com/facebookresearch/SentEval/tree/main/data/probing
McCoy et al. (2020) dataset: https://github.com/tommccoy1/rnn-hierarchical-biases

- [x] Collect both datasets and put them into the repository
- [x] Transform into a common format

**Comment by lurr98** [comment]
I brought the data from McCoy et al. (2020) into the same format as the files from Conneau et al. (2018) (`.txt` files)

Format is:

```
**(tr|te|va)**\t**target**\t**item**
```

Data from Conneau et al. (2018) can be found in `data/probing_data`.
Original data from McCoy et al. (2020) can be found in `data/original_pov_data`.
Data from  McCoy et al. (2020) in new, unified format can be found in `data/new_pov_data`. There are three files, each prepared for one of the three probing tasks:

1. predict main auxiliary
2. predict fourth word
3. predict second word
