### ISSUE TITLE
Retrieving sentence representations from Transformer model

### ISSUE THREAD

**Issue by urbikn** [urbikn/probing-hierarchical-sentences#2]
- [x] Setting up virtual environment with needed libraries: transformers, pytorch, etc
- [x] Setting up script to retrieve and store sentence representations using `BERT-base-cased` (save all output embeddings in case we change the project, not only [CLS] token embedding)
- [x] Rewrite script to be able to read dataset format and store actual representations

**Comment by lurr98** [comment]
Pado said CLS token is not a good representation (https://aclanthology.org/2023.eacl-main.268), so use SBERT instead!

**Comment by urbikn** [comment]
## Suggestion: making a comparison between a BiLSTM and SBERT model.

To obtain sentence representations for the BiLSTM model, we used the weights of a model trained on NLI. The encoder was described in [Conneau et al., 2017](https://aclanthology.org/D17-1070/) and is cited as a reference in the $&!#*  paper. The model has approximately 38 million parameters.

For the SBERT model, we used the [MiniLM](https://huggingface.co/sentence-transformers/paraphrase-MiniLM-L12-v2) model, which was distilled from a larger model and further trained on multiple tasks, including NLI. The model has approximately 34 million parameters.

Both models have comparable parameter sizes and were trained on the same data for the same task. This enables us to reproduce the work from the $&!#*  paper while also extending it to SBERT.

**Comment by urbikn** [comment]
Closed with commit  99ce792
